### ISSUE TITLE
put: command not found on Centos 6

### ISSUE THREAD

**Issue by ecowebdesign** [Pe46dro/Bash-MySQL-Database-SFTP-FTP-Backup#5]
./script.sh: line (66): put: command not found

**Comment by AppFull** [comment]
debian either, the local backup is working, just the remote problem 'put not a command' 
SFTP with different port?

**Comment by ecowebdesign** [comment]
I have a port 222 for remote server

I modified your code like this 


sshpass -p $PASSWORD ssh -p 222 $USERNAME@$SERVER
# sshpass -p $PASSWORD $USERNAME@$SERVER

**Comment by Pe46dro** [comment]
Custom port support added in commit "d3e24cb"
I will check for put command error

**Comment by AppFull** [comment]
rsync is better solution :eggplant:

**Comment by ecowebdesign** [comment]
I have tried it again ...  PUT command not found..apparently my system don't understand to understand it.

this worked for me:
replaced 

#cd $backup_path
#sshpass -p $PASSWORD ssh -p $PORT $USERNAME@$SERVER
#cd $REMOTDIR
# put $FILE

with rsync --rsh="sshpass -p  $PASSWORD ssh -p $PORT -o StrictHostKeyChecking=no -l $USERNAME" $backup_path/$FILE  $SERVER:$REMOTEDIR

**Comment by Pe46dro** [comment]
@ecowebdesign i have do some test and it work fine, i will replace PUT whit rsync
